### ISSUE TITLE
Is this musickit v1 or v3?

### ISSUE THREAD

**Issue by tscanlon** [Exerra/node-musickit-api#8]
My apologies I was looking for an npm library to work with MusicKit and haven't worked with JS before. I was trying to see if your library was based off of the v1 endpoint or the v3 endpoint. There aren't very clear timestamps on when v3 was released but my best guess is about 2mo after the bulk of your work in this based on commits. 

https://js-cdn.music.apple.com/musickit/v3/docs/index.html?path=/story/tech-notes-migrating-to-v3--page

Thanks for your time, 
Tom.

**Comment by Exerra** [comment]
Hello Tom,

This package is using the `v1` endpoint as the [Apple documentation](https://developer.apple.com/documentation/applemusicapi/handling_requests_and_responses) only shows the `v1` endpoint. If the docs ever get updated with newer endpoint versions, I will update the code to use the newest endpoint in the documentation (& perhaps even rewrite it in Typescript)
