### ISSUE TITLE
Personalized Endpoints

### ISSUE THREAD

**Issue by wont-stream** [Exerra/node-musickit-api#9]
I saw in the docs you have not yet added those yet
"
[Adding personalized routes](https://musickit.js.org/#/?id=adding-personalized-routes)

Currently node-musickit-api doesn't support personalized routes (api.music.apple.com/v1/me)

It is going to require quite some work to support those routes, but I am certain I could pull it off
"

and was wondering if you have an ETA? I haven't found any other packages that support this yet and I'm relying one something for my API.

Thanks

**Comment by Exerra** [comment]
Yeah, sorry, I no longer have a paid Apple developer account so I cannot continue development on this myself. There are hacky workarounds with using the [Apple Musickit JS lib](https://developer.apple.com/documentation/musickitjs) to grab the user token and then using it in my package, but as I said, that is hacky and might not work.

This thread might have more info about it https://github.com/FoxxMD/multi-scrobbler/issues/9
